# District 1: Missing RT https://github.com/cal-itp/gtfs-curator/issues/82

In [49]:
from functools import cache
from pathlib import Path

import pandas as pd
import google.auth
import geopandas as gpd

from calitp_data_analysis.gcs_pandas import GCSPandas
from calitp_data_analysis.sql import get_engine

# from shared_utils import bq_utils
# Initialize credentials and DB engine
credentials, project = google.auth.default()
db_engine = get_engine()

import _prep_crosswalk_ntd
import _load_gtfs_data
from update_vars import DIGEST_DICT

In [2]:
from update_vars import DIGEST_DICT as GTFS_DATA_DICT, abbrev_month, analysis_month

In [3]:
@cache
def gcs_pandas():
    return GCSPandas()

In [4]:
pd.options.display.max_columns = 100
pd.options.display.float_format = "{:.2f}".format
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

In [5]:
agencies_with_rt = ["Humboldt Transit Authority",
                   "Lake Transit Authority",
                   "Redwood Coast Transit Authority"]

In [6]:
raw_url = "gs://calitp-analytics-data/data-analyses/gtfs_digest/raw/fct_monthly_operator_summary_2026_08.parquet"

In [7]:
fct_monthly_route_df = pd.read_parquet(raw_url,
                                        storage_options={"token": credentials.token}).reset_index()

In [8]:
fct_monthly_route_df.sample()

,index,month,year,month_first_day,schedule_name,schedule_base64_url,vp_name,vp_base64_url,tu_name,tu_base64_url,day_type,n_trips,daily_trips,ttl_service_hours,daily_service_hours,ttl_flex_service_hours,daily_flex_service_hours,n_routes,n_shapes,n_stops,num_stop_times,daily_arrivals,n_days,n_feeds,vp_messages_per_minute,n_vp_trips,daily_vp_trips,pct_vp_trips,pct_vp_routes,daily_vp_extract_duration_minutes,tu_messages_per_minute,n_tu_trips,daily_tu_trips,pct_tu_trips,pct_tu_routes,daily_tu_extract_duration_minutes,pct_tu_complete_minutes,pct_tu_accurate_minutes,avg_prediction_spread_minutes,n_predictions,pct_predictions_early,pct_predictions_ontime,pct_predictions_late,n_days_schedule_only,n_days_schedule_and_rt,n_days_schedule_and_vp_only,n_days_schedule_and_tu_only,prediction_error_sec_array,prediction_error_sec_percentile_array,scaled_prediction_error_sec_array,pos_prediction_error_sec_array,neg_prediction_error_sec_array,pos_prediction_error_sec_percentile_array
2062,2062,8,2026,2026-08-01,B-Line Schedule,aHR0cHM6Ly9wbGFubXlyaWRlLmJsaW5ldHJhbnNpdC5jb20vZ3Rmc3JlYWx0aW1lL2dvb2dsZV90cmFuc2l0LnppcA==,B-Line Vehicle Positions,aHR0cHM6Ly9wbGFubXlyaWRlLmJsaW5ldHJhbnNpdC5jb20vZ3Rmc3JlYWx0aW1lL0dURlNfVmVoaWNsZVBvc2l0aW9ucy5wYg==,B-Line Trip Updates,aHR0cHM6Ly9wbGFubXlyaWRlLmJsaW5ldHJhbnNpdC5jb20vZ3Rmc3JlYWx0aW1lL0dURlNfVHJpcFVwZGF0ZXMucGI=,Sunday,50,10.00,45.90,9.20,0.00,0.00,1,2,55,1550,310.00,5,2,3.00,50,10.00,1.00,1.00,598.20,2.90,50,10.00,1.00,1.00,1764.40,1.00,0.75,0.20,61456.00,0.51,0.03,0.47,0.00,5.00,0.00,0.00,"[-230.3, -164.0, -104.0, -80.3, -58.0, -19.0, 3.3, 29.0, 63.7, 82.0, 102.0, 216.0, 356.0]","[5, 10, 20, 25, 30, 40, 50, 60, 70, 75, 80, 90, 95]","[-0.477, -0.267, -0.127, -0.098, -0.075, -0.028, 0.004, 0.042, 0.081, 0.111, 0.155, 0.295, 0.44]","[7.0, 13.0, 26.7, 36.0, 44.0, 61.0, 80.0, 100.0, 139.3, 165.0, 213.0, 355.0, 451.7]","[-400.0, -241.3, -171.0, -153.7, -137.7, -110.0, -87.0, -68.7, -47.0, -36.7, -29.3, -14.7, -6.7]","[95, 90, 80, 75, 70, 60, 50, 40, 30, 25, 20, 10, 5]"

In [15]:
fct_monthly_route_df.schedule_name.unique()

array(['Yuba-Sutter Schedule', 'Petaluma GMV Schedule',
       'Anteater Express Schedule', 'MVGO Schedule', 'Calaveras Schedule',
       'Lake Schedule', 'Artesia Schedule', 'YARTS Schedule',
       'Bay Area 511 Emery Express Schedule', 'ACE Schedule',
       'Roseville Transit TripShot Schedule',
       'Bay Area 511 Fairfield and Suisun Transit Schedule',
       'Lassen Schedule', 'CSULB Shuttle PassioGo Schedule',
       'Clovis Schedule', 'WestCAT Flex', 'Wasco DAR Schedule',
       'Curry Public Transit Schedule', 'Alhambra Schedule',
       'Glendora Schedule', 'San Juan Capistrano Trolley Schedule',
       'La Puente Schedule', 'Bay Area 511 MVGO Schedule',
       'Eastern Sierra Flex', 'Moorpark Schedule', 'Delano Schedule',
       'Madera Metro Schedule', 'Trinity Remix Schedule',
       'Bellflower Remix Schedule', 'El Segundo Schedule',
       'Rio Vista Schedule', 'Tri-Valley Wheels Schedule',
       'Thousand Oaks Flex', 'Compton Schedule', 'Turlock Flex',
       'Calabasas Schedule', 'Get Around Town Express Schedule',
       'Camarillo Schedule', 'VCTC Schedule', 'TART Flex',
       'Redwood Coast Schedule',
       'Bay Area 511 Vacaville City Coach Schedule',
       'Thousand Oaks Schedule', 'Huntington Park Schedule',
       'Plumas Schedule', 'Inglewood Schedule', 'AC Transit Schedule',
       'Tracy Flex', 'Turlock Schedule', 'Bell Gardens Schedule',
       'Oregon POINT', 'Bay Area 511 BART Schedule',
       'LA Metro Rail Schedule', 'eTrans Schedule Remix',
       'Tehama Schedule', 'Desert Roadrunner GMV Schedule',
       'Sacramento Airport Park & Ride Schedule', 'Lake Schedule Remix',
       'OmniTrans Schedule', 'Merced Schedule',
       'Palos Verdes PTA Schedule', 'BART Schedule', 'Redwood Coast Flex',
       'Redding Schedule', 'Bay Area 511 Commute.org Schedule',
       'TCAT Flex', 'Vine GMV Schedule', 'Bay Area 511 Regional Schedule',
       'StanRTA Flex', 'Placer Flex', 'BruinBus Schedule',
       'Bay Area 511 Capitol Corridor Schedule', 'El Monte Schedule',
       'Emery Go-Round Schedule', 'Beaumont Transit Schedule',
       'Maywood Schedule', 'Mendocino Schedule Remix',
       'Baldwin Park Schedule', 'Havasu Landing Ferry Schedule',
       'County Connection Schedule',
       'Balboa Peninsula Trolley Passio Schedule',
       'Bay Area 511 Dumbarton Express Schedule', 'VCTC Flex',
       'Petaluma Schedule',
       'Bay Area 511 Rio Vista Delta Breeze Schedule',
       'Vacaville Schedule', 'LA Metro Events Schedule',
       'University of San Diego Tram Services Schedule',
       'Merced GMV Schedule', 'Commute.org Schedules',
       'San Joaquin Schedule', 'Bay Area 511 Petaluma Schedule',
       'Kern Schedule', 'San Joaquin Flex',
       'Bay Area 511 Santa Rosa CityBus Schedule', 'Manteca Flex',
       'Elk Grove Schedule', 'Glenn Schedule', 'Arvin Schedule',
       'Sacramento Schedule', 'Bay Area 511 SolTrans Schedule',
       'Union City Flex', 'Corona Schedule', 'Long Beach Schedule',
       'Placer Schedule', 'G Trans Schedule',
       'Bay Area 511 Mission Bay Schedule', 'Carson Circuit Schedule',
       'Desert Roadrunner Schedule', 'Laguna Beach Flex',
       'Bay Area 511 County Connection Schedule',
       'South County Transit Link Schedule', 'Tracy Schedule',
       'Bay Area 511 ACE Schedule', 'Fairfield Schedule', 'Humboldt Flex',
       'Roseville Schedule', 'Blossom Express Schedule',
       'Sage Stage Schedule', 'Siskiyou Schedule', 'Lassen Flex',
       'Golden Gate Park Shuttle Schedule', 'San Pedro Trolley Schedule',
       'Lassen Schedule Remix', 'Bulldog Express PassioGo Schedule',
       'Laguna Niguel Trolley PassioGo Schedule', 'Lompoc Schedule',
       'Fric and Frac Schedule', 'Fresno County Schedule',
       'Banning Pass Schedule', 'UCSC Schedule', 'Stanislaus Flex',
       'Emery Go-Round TripShot Schedule', 'Yurok Schedule',
       'Ridgecrest Schedule', 'SBMTD Schedule', 'Fresno Schedule',
       'DowneyLink Avail Schedule', 'Redding Flex',
       'Mission Bay Schedule', 'Manteca Schedule',
       'Santa Ynez Mecatran Schedule', 'Clean Air Express Schedule',
       'Bay Area 511 Sonoma County Transit Schedule',
       'Redwood Coast Schedule Remix',
       'Bay Area 511 South San Francisco Shuttle Schedule',
       'Bay Area 511 Santa Cruz Metro Schedule', 'San Diego Schedule',
       'Tuolumne Remix Schedule', 'Kings Schedule', 'Burbank Schedule',
       'Bay Area 511 Emery Go-Round Schedule', 'North County Schedule',
       'Victor Valley GMV Schedule', 'Spirit Bus Passio Schedule',
       'Yuba-Sutter PassioGo Schedule', 'Go West Schedule',
       'Mountain Transit GMV Schedule', 'South San Francisco Schedule',
       'Mendocino Schedule', 'Amador Schedule', 'B-Line Schedule',
       'La Campana Schedule', 'Torrance Schedule',
       'Bay Area 511 Vine Transit Schedule', 'Humboldt Schedule',
       'OCTA Schedule', 'LA DOT Schedule', 'SolTrans Schedule',
       'CatTracks Schedule', 'Bay Area 511 Marin Schedule',
       'Norwalk Avail Schedule', 'Clovis PassioGo Schedule',
       'Riverside Schedule', 'SCVTA Schedule', 'Simi Valley Schedule',
       'Madera County Connection Schedule', 'Triton Transit Schedule',
       'Pasadena Schedule', 'Culver City Schedule',
       'Bay Area 511 AC Transit Schedule', 'Big Blue Bus Schedule',
       'SLORTA Schedule', 'Needles Schedule',
       'Bay Area 511 Muni Schedule', 'Santa Maria Schedule',
       'Yuma Schedule', 'Santa Rosa CityBus GMV Schedule',
       'Stanford Schedule', 'County Express Schedule', 'StanRTA Schedule',
       'San Joaquin Paratransit', 'Yurok Ferry Schedule',
       'Bay Area 511 Angel Island-Tiburon Ferry Schedule',
       'El Dorado Schedule', 'Yurok Bus Schedule',
       'County Express Schedule Remix',
       'Bay Area 511 Treasure Island Ferry Schedule',
       'Long Beach Transit Water Taxis GTFS Schedule',
       'Bay Area 511 Golden Gate Ferry Schedule',
       'Mariposa Grove Shuttle Schedule', 'Capitol Corridor Schedule',
       'Bay Area 511 Golden Gate Park Shuttle Schedule',
       'Morongo Basin Schedule', 'Imperial Valley Transit Schedule',
       'San Fernando Schedule', 'VCTC Intercity Schedule',
       'Cudahy Schedule', 'Peppedine University Shuttles Schedule',
       'Bear Schedule', 'Gold Runner Schedule', 'Lawndale Schedule',
       'Bay Area 511 Mountain View Community Shuttle Schedule',
       'Dana Point Trolley PassioGo Schedule', 'Arcadia Schedule',
       'San Diego International Airport Shuttles Schedule',
       'Basin Transit GMV Schedule', 'Lynwood Schedule IPS',
       'Irvine CONNECT Schedule', 'MV Shuttle Schedule', 'WeHo Schedule',
       'WestCAT Schedule', 'Union City TripShot Schedule',
       'San Clemente Trolley Schedule', 'LAX Flyaway Bus Schedule',
       'Yosemite Valley Shuttle Schedule', 'Grapeline Schedule',
       'Caltrain Schedule', 'Tahoe Transportation District Schedule',
       'El Monte RTAP Schedule', 'Vine Schedule', 'Laguna Beach Schedule',
       'Mountain Transit Schedule', 'Mountain Transit Schedule Remix',
       'LADPW Schedule', 'TART, North Lake Tahoe Schedule',
       'Glendale Schedule', 'Commerce Schedule', 'Sonoma Schedule',
       'TCRTA Schedule', 'Gold Coast Schedule',
       'Bay Area 511 Union City Transit Schedule',
       'Golden Gate Bridge Schedule', 'Amtrak Schedule',
       'Flixbus Schedule', 'Bay Area 511 Tri-Valley Wheels Schedule',
       'VCTC GMV Schedule', 'Sonoma County Transit Schedule',
       'Victor Valley Schedule', 'Bay Area 511 Tri Delta Schedule',
       'Visalia Schedule', 'Antelope Valley Transit Authority Schedule',
       'SunLine Avail Schedule', 'Monterey Salinas Schedule',
       'Montebello Schedule', 'SamTrans Schedule', 'Foothill Schedule',
       'LAX Shuttles Schedule',
       'Tahoe Transportation District GMV Schedule',
       'Bay Area 511 Caltrain Schedule',
       'Bay Area 511 Golden Gate Transit Schedule',
       'Bay Area 511 PresidiGo Schedule',
       'Bay Area 511 Sonoma-Marin Area Rail Transit Schedule',
       'Bay Area 511 San Francisco Bay Ferry Schedule',
       'Bay Area 511 Santa Clara Transit Schedule',
       'Bay Area 511 SFO AirTrain Schedule',
       'Bay Area 511 SamTrans Schedule', 'Bay Area 511 WestCAT Schedule',
       'Nevada County Remix Schedule', 'Eastern Sierra Schedule',
       'LA Metro Bus Schedule', 'SMART Schedule',
       'San Francisco Bay Ferry Schedule', 'Redding Schedule Remix',
       'Unitrans Schedule', 'Santa Clarita Schedule', 'Yolobus Schedule',
       'GET Schedule', 'Marin Optibus Schedule', 'Metrolink Schedule',
       'Mountain View Community Shuttle Schedule', 'PresidiGo Schedule',
       'Beach Cities GMV Schedule', 'Lawndale Beat GMV Schedule',
       'Santa Cruz Schedule', 'Tri Delta Connexionz Schedule',
       'SLO Connexionz Schedule', 'SunLine GMV Schedule'], dtype=object)

In [9]:
fct_monthly_route_df2 = fct_monthly_route_df.loc[fct_monthly_route_df.schedule_name.isin(
 ["Lake Schedule"] 
)]

In [10]:
fct_monthly_route_df2.sample()

,index,month,year,month_first_day,schedule_name,schedule_base64_url,vp_name,vp_base64_url,tu_name,tu_base64_url,day_type,n_trips,daily_trips,ttl_service_hours,daily_service_hours,ttl_flex_service_hours,daily_flex_service_hours,n_routes,n_shapes,n_stops,num_stop_times,daily_arrivals,n_days,n_feeds,vp_messages_per_minute,n_vp_trips,daily_vp_trips,pct_vp_trips,pct_vp_routes,daily_vp_extract_duration_minutes,tu_messages_per_minute,n_tu_trips,daily_tu_trips,pct_tu_trips,pct_tu_routes,daily_tu_extract_duration_minutes,pct_tu_complete_minutes,pct_tu_accurate_minutes,avg_prediction_spread_minutes,n_predictions,pct_predictions_early,pct_predictions_ontime,pct_predictions_late,n_days_schedule_only,n_days_schedule_and_rt,n_days_schedule_and_vp_only,n_days_schedule_and_tu_only,prediction_error_sec_array,prediction_error_sec_percentile_array,scaled_prediction_error_sec_array,pos_prediction_error_sec_array,neg_prediction_error_sec_array,pos_prediction_error_sec_percentile_array
5,5,8,2026,2026-08-01,Lake Schedule,None,None,None,None,None,Sunday,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0.00,5,1,NaN,0,0.00,NaN,NaN,NaN,NaN,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],[],[],[]

In [11]:
fct_monthly_route_df2.filter(like="vp").columns

Index(['vp_name', 'vp_base64_url', 'vp_messages_per_minute', 'n_vp_trips',
       'daily_vp_trips', 'pct_vp_trips', 'pct_vp_routes',
       'daily_vp_extract_duration_minutes', 'n_days_schedule_and_vp_only'],
      dtype='object')

In [12]:
fct_monthly_route_df2.pct_vp_trips.describe()

count   0.00
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: pct_vp_trips, dtype: float64

In [13]:
fct_monthly_route_df2.pct_vp_routes.describe()

count   0.00
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: pct_vp_routes, dtype: float64

In [14]:
fct_monthly_route_df2.vp_messages_per_minute.describe()

count   0.00
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: vp_messages_per_minute, dtype: float64

# Also noticed a lot of AC Transit RT is missing
* My code is dropping the previous months with data.

##  VP and TU Missing

In [20]:
operator_summary_url = "gs://calitp-analytics-data/data-analyses/gtfs_digest/raw/fct_monthly_operator_summary_2026_08.parquet"

In [22]:
operator_df = gcs_pandas().read_parquet(
    operator_summary_url)

In [23]:
operator_df.sample()

,month,year,month_first_day,schedule_name,schedule_base64_url,vp_name,vp_base64_url,tu_name,tu_base64_url,day_type,n_trips,daily_trips,ttl_service_hours,daily_service_hours,ttl_flex_service_hours,daily_flex_service_hours,n_routes,n_shapes,n_stops,num_stop_times,daily_arrivals,n_days,n_feeds,vp_messages_per_minute,n_vp_trips,daily_vp_trips,pct_vp_trips,pct_vp_routes,daily_vp_extract_duration_minutes,tu_messages_per_minute,n_tu_trips,daily_tu_trips,pct_tu_trips,pct_tu_routes,daily_tu_extract_duration_minutes,pct_tu_complete_minutes,pct_tu_accurate_minutes,avg_prediction_spread_minutes,n_predictions,pct_predictions_early,pct_predictions_ontime,pct_predictions_late,n_days_schedule_only,n_days_schedule_and_rt,n_days_schedule_and_vp_only,n_days_schedule_and_tu_only,prediction_error_sec_array,prediction_error_sec_percentile_array,scaled_prediction_error_sec_array,pos_prediction_error_sec_array,neg_prediction_error_sec_array,pos_prediction_error_sec_percentile_array
601,9,2026,2026-09-01,LA Metro Events Schedule,None,None,None,None,None,Weekday,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0.00,3,2,NaN,0,0.00,NaN,NaN,NaN,NaN,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],[],[],[]

In [25]:
ac_transit = operator_df.loc[operator_df.schedule_name == "Bay Area 511 AC Transit Schedule"]

In [29]:
ac_transit.sample()

,month,year,month_first_day,schedule_name,schedule_base64_url,vp_name,vp_base64_url,tu_name,tu_base64_url,day_type,n_trips,daily_trips,ttl_service_hours,daily_service_hours,ttl_flex_service_hours,daily_flex_service_hours,n_routes,n_shapes,n_stops,num_stop_times,daily_arrivals,n_days,n_feeds,vp_messages_per_minute,n_vp_trips,daily_vp_trips,pct_vp_trips,pct_vp_routes,daily_vp_extract_duration_minutes,tu_messages_per_minute,n_tu_trips,daily_tu_trips,pct_tu_trips,pct_tu_routes,daily_tu_extract_duration_minutes,pct_tu_complete_minutes,pct_tu_accurate_minutes,avg_prediction_spread_minutes,n_predictions,pct_predictions_early,pct_predictions_ontime,pct_predictions_late,n_days_schedule_only,n_days_schedule_and_rt,n_days_schedule_and_vp_only,n_days_schedule_and_tu_only,prediction_error_sec_array,prediction_error_sec_percentile_array,scaled_prediction_error_sec_array,pos_prediction_error_sec_array,neg_prediction_error_sec_array,pos_prediction_error_sec_percentile_array
512,8,2026,2026-08-01,Bay Area 511 AC Transit Schedule,None,None,None,None,None,Weekday,0,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0.00,1,1,NaN,0,0.00,NaN,NaN,NaN,NaN,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[],[],[],[],[],[]

In [31]:
ac_transit2 = ac_transit.dropna(subset = ["n_vp_trips","pct_vp_trips","pct_tu_trips","pct_tu_routes"])

In [30]:
ac_transit[["day_type","month_first_day","n_vp_trips","pct_vp_trips","pct_tu_trips","pct_tu_routes"]].sort_values(by = ["month_first_day"])

,day_type,month_first_day,n_vp_trips,pct_vp_trips,pct_tu_trips,pct_tu_routes
1488,Saturday,2026-07-01,14193,0.89,0.98,1.00
1489,Sunday,2026-07-01,12110,0.76,0.91,1.00
1490,Weekday,2026-07-01,104132,0.92,0.99,1.00
509,Saturday,2026-08-01,0,NaN,NaN,NaN
512,Weekday,2026-08-01,0,NaN,NaN,NaN
1486,Saturday,2026-08-01,14376,0.90,0.98,1.00
1487,Sunday,2026-08-01,16875,0.84,0.96,1.00
1491,Weekday,2026-08-01,93302,0.92,0.98,1.00
1485,Weekday,2026-09-01,10016,0.92,0.99,1.00

In [34]:
GCS_PATH = f"{GTFS_DATA_DICT.dir}processed/"

In [35]:
f"{GCS_PATH}{GTFS_DATA_DICT.schedule_rt_route_direction}.parquet"

'gs://calitp-analytics-data/data-analyses/gtfs_digest/processed/fct_monthly_schedule_rt_route_direction_summary.parquet'

In [36]:
ac_transit2 = ac_transit2.loc[ac_transit2.day_type == "Weekday"]

In [37]:
ac_transit2[["day_type","month_first_day","n_vp_trips","pct_vp_trips","pct_tu_trips","pct_tu_routes"]].sort_values(by = ["month_first_day"])

,day_type,month_first_day,n_vp_trips,pct_vp_trips,pct_tu_trips,pct_tu_routes
1490,Weekday,2026-07-01,104132,0.92,0.99,1.00
1491,Weekday,2026-08-01,93302,0.92,0.98,1.00
1485,Weekday,2026-09-01,10016,0.92,0.99,1.00

In [ ]:
operator_df = gcs_pandas().read_parquet(
    operator_summary_url,
    filters=[
        ("Day Type", "==", "Weekday"),
        ("Analysis Name", "==", analysis_name)],
).drop_duplicates(subset = ["Analysis Name", "Date"])

In [39]:
import _new_operator_report_utils as utils

## Scheduled Route Direction Summary

In [52]:
"gs://calitp-analytics-data/data-analyses/gtfs_digest/raw/fct_monthly_schedule_rt_route_direction_summary_2026_08.parquet"

'gs://calitp-analytics-data/data-analyses/gtfs_digest/raw/fct_monthly_schedule_rt_route_direction_summary_2026_08.parquet'

In [53]:
DIGEST_DICT.schedule_rt_route_direction

'fct_monthly_schedule_rt_route_direction_summary'

In [60]:
df = gcs_pandas().read_parquet("gs://calitp-analytics-data/data-analyses/gtfs_digest/raw/fct_monthly_schedule_rt_route_direction_summary_2026_08.parquet"
    )

In [61]:
df.columns

Index(['month', 'year', 'month_first_day', 'day_type', 'schedule_base64_url',
       'name', 'tu_base64_url', 'tu_name', 'vp_base64_url', 'vp_name',
       'route_name', 'direction_id', 'route_type', 'n_trips',
       'daily_trips_all_day', 'n_route_ids', 'n_shapes', 'avg_stops_served',
       'ttl_service_hours', 'ttl_flex_service_hours', 'daily_service_hours',
       'daily_flex_service_hours', 'n_feeds', 'n_days', 'daily_trips_owl',
       'daily_trips_early_am', 'daily_trips_am_peak', 'daily_trips_midday',
       'daily_trips_pm_peak', 'daily_trips_evening', 'daily_trips_peak',
       'daily_trips_offpeak', 'frequency_owl', 'frequency_early_am',
       'frequency_am_peak', 'frequency_midday', 'frequency_pm_peak',
       'frequency_evening', 'frequency_peak', 'frequency_offpeak',
       'frequency_all_day', 'appeared_in_tu', 'appeared_in_vp',
       'vp_num_distinct_updates', 'n_vp_trips', 'vp_extract_duration_minutes',
       'vp_messages_per_minute', 'tu_num_distinct_updates', 'n_tu_trips',
       'tu_extract_duration_minutes', 'tu_messages_per_minute',
       'route_typology'],
      dtype='object')

In [62]:
schedule_route_dir_columns_to_keep = [
                "month_first_day",
                "name",
                "route_name",
                "direction_id",
                "frequency_all_day",
                "frequency_offpeak",
                "frequency_peak",
                "daily_trips_peak",
                "daily_trips_offpeak",
                "daily_trips_all_day",
                "day_type",
                "route_type",
                "daily_service_hours",
                "route_typology",
            ]

In [63]:
df = df[schedule_route_dir_columns_to_keep]

In [65]:
df = df.loc[df.name.isin(['Bay Area 511 AC Transit Schedule',
       'AC Transit Schedule'])]

In [66]:
df.shape

(8990, 14)

In [69]:
df[["month_first_day","route_name","frequency_all_day",
                "frequency_offpeak",
                "frequency_peak","daily_service_hours",
   ]].sort_values(by = ["month_first_day","route_name"], 
                  ascending =  [False, False])

       month_first_day                                 route_name  \
18811       2026-09-01       W__W Bay Farm - South Shore Transbay
18825       2026-09-01       W__W Bay Farm - South Shore Transbay
55441       2026-09-01       W__W Bay Farm - South Shore Transbay
55455       2026-09-01       W__W Bay Farm - South Shore Transbay
34244       2026-09-01       V__V Montclair - Park Blvd. Transbay
34248       2026-09-01       V__V Montclair - Park Blvd. Transbay
47770       2026-09-01       V__V Montclair - Park Blvd. Transbay
47783       2026-09-01       V__V Montclair - Park Blvd. Transbay
34179       2026-09-01        U__U Stanford - Dumbarton - Fremont
34184       2026-09-01        U__U Stanford - Dumbarton - Fremont
47581       2026-09-01        U__U Stanford - Dumbarton - Fremont
47584       2026-09-01        U__U Stanford - Dumbarton - Fremont
54682       2026-09-01      P__P Piedmont - Oakland Ave. Transbay
54688       2026-09-01      P__P Piedmont - Oakland Ave. Transbay
83371       2026-09-01      P__P Piedmont - Oakland Ave. Transbay
83376       2026-09-01      P__P Piedmont - Oakland Ave. Transbay
127901      2026-09-01        O__O Santa Clara - Encinal Transbay
127904      2026-09-01        O__O Santa Clara - Encinal Transbay
128933      2026-09-01        O__O Santa Clara - Encinal Transbay
128935      2026-09-01        O__O Santa Clara - Encinal Transbay
26292       2026-09-01       NX__NX Grand Lake - Laurel  Transbay
26297       2026-09-01       NX__NX Grand Lake - Laurel  Transbay
46830       2026-09-01       NX__NX Grand Lake - Laurel  Transbay
46844       2026-09-01       NX__NX Grand Lake - Laurel  Transbay
26265       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
26268       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
26277       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
26284       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
46823       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
46825       2026-09-01     NX3__NX3 MacArthur - Eastmont Transbay
143756      2026-09-01          NL__NL MacArthur Transbay Limited
143758      2026-09-01          NL__NL MacArthur Transbay Limited
143762      2026-09-01          NL__NL MacArthur Transbay Limited
143767      2026-09-01          NL__NL MacArthur Transbay Limited
26150       2026-09-01           L__L San Pablo - Pierce Transbay
26154       2026-09-01           L__L San Pablo - Pierce Transbay
40113       2026-09-01           L__L San Pablo - Pierce Transbay
40118       2026-09-01           L__L San Pablo - Pierce Transbay
40077       2026-09-01       J__J Sacramento -  Christie Transbay
40080       2026-09-01       J__J Sacramento -  Christie Transbay
46630       2026-09-01       J__J Sacramento -  Christie Transbay
46635       2026-09-01       J__J Sacramento -  Christie Transbay
46534       2026-09-01              G__G Colusa - Solano Transbay
46538       2026-09-01              G__G Colusa - Solano Transbay
46544       2026-09-01              G__G Colusa - Solano Transbay
46546       2026-09-01              G__G Colusa - Solano Transbay
46549       2026-09-01              G__G Colusa - Solano Transbay
46556       2026-09-01              G__G Colusa - Solano Transbay
127872      2026-09-01             F__F Adeline - Market Transbay
127873      2026-09-01             F__F Adeline - Market Transbay
132295      2026-09-01             F__F Adeline - Market Transbay
132296      2026-09-01             F__F Adeline - Market Transbay
17178       2026-09-01      FS__FS Shattuck - University Transbay
17184       2026-09-01      FS__FS Shattuck - University Transbay
26034       2026-09-01      FS__FS Shattuck - University Transbay
26043       2026-09-01      FS__FS Shattuck - University Transbay
25906       2026-09-01       E__E Tunnel Rd. - Claremont Transbay
25914       2026-09-01       E__E Tunnel Rd. - Claremont Transbay
46447       2026-09-01       E__E Tunnel Rd. - Claremont Transbay
46449       2026-09-01       E__E Tunnel Rd. - Claremont Transbay
149767      2026-09-01                 9__9 E. 14th St. - Mission
149779      2026-09-01                 9__9 E. 14th St. - Mission
149783      2026-09-01                 9__9 E. 14th St. - Mission
149784      2026-09-01                 9__9 E. 14th St. - Mission
139278      2026-09-01    98__98 Eastmont - 98th Ave. - Edgewater
139281      2026-09-01    98__98 Eastmont - 98th Ave. - Edgewater
139285      2026-09-01    98__98 Eastmont - 98th Ave. - Edgewater
139293      2026-09-01    98__98 Eastmont - 98th Ave. - Edgewater
142774      2026-09-01       97__97 Hesperian - Alvarado - Decoto
142776      2026-09-01       97__97 Hesperian - Alvarado - Decoto
144002      2026-09-01       97__97 Hesperian - Alvarado - Decoto
144003      2026-09-01       97__97 Hesperian - Alvarado - Decoto
123265      2026-09-01    96__96 Alameda Pt. - 14th Ave. - Dimond
123296      2026-09-01    96__96 Alameda Pt. - 14th Ave. - Dimond
123339      2026-09-01    96__96 Alameda Pt. - 14th Ave. - Dimond
123345      2026-09-01    96__96 Alameda Pt. - 14th Ave. - Dimond
99395       2026-09-01             95__95 D St. - Maud - Fairview
99396       2026-09-01             95__95 D St. - Maud - Fairview
102783      2026-09-01             95__95 D St. - Maud - Fairview
102786      2026-09-01             95__95 D St. - Maud - Fairview
96655       2026-09-01       93__93 Ashland - San Lorenzo - A St.
96656       2026-09-01       93__93 Ashland - San Lorenzo - A St.
98739       2026-09-01       93__93 Ashland - San Lorenzo - A St.
98740       2026-09-01       93__93 Ashland - San Lorenzo - A St.
139246      2026-09-01    90__90 85th Ave. - Elmhurst - 90th Ave.
139247      2026-09-01    90__90 85th Ave. - Elmhurst - 90th Ave.
139255      2026-09-01    90__90 85th Ave. - Elmhurst - 90th Ave.
139260      2026-09-01    90__90 85th Ave. - Elmhurst - 90th Ave.
139177      2026-09-01    88__88 Sacramento - Market- Oakland Ave
139183      2026-09-01    88__88 Sacramento - Market- Oakland Ave
139184      2026-09-01    88__88 Sacramento - Market- Oakland Ave
139190      2026-09-01    88__88 Sacramento - Market- Oakland Ave
107225      2026-09-01      86__86 Winton - Industrial - Tennyson
107226      2026-09-01      86__86 Winton - Industrial - Tennyson
107227      2026-09-01      86__86 Winton - Industrial - Tennyson
107232      2026-09-01      86__86 Winton - Industrial - Tennyson
3458        2026-09-01  851__851 Santa Clara-Broadway All Nighter
3463        2026-09-01  851__851 Santa Clara-Broadway All Nighter
3551        2026-09-01  851__851 Santa Clara-Broadway All Nighter
3557        2026-09-01  851__851 Santa Clara-Broadway All Nighter
3340        2026-09-01   840__840 Foothill - Eastmont All Nighter
3393        2026-09-01   840__840 Foothill - Eastmont All Nighter
3404        2026-09-01   840__840 Foothill - Eastmont All Nighter
3440        2026-09-01   840__840 Foothill - Eastmont All Nighter
3224        2026-09-01   805__805 MacArthur - Airport All Nighter
3227        2026-09-01   805__805 MacArthur - Airport All Nighter
3284        2026-09-01   805__805 MacArthur - Airport All Nighter
3298        2026-09-01   805__805 MacArthur - Airport All Nighter
3101        2026-09-01             802__802 San Pablo All Nighter
3103        2026-09-01             802__802 San Pablo All Nighter
3126        2026-09-01             802__802 San Pablo All Nighter
3176        2026-09-01             802__802 San Pablo All Nighter
3007        2026-09-01     801__801 E 14th - Mission  All Nighter
3043        2026-09-01     801__801 E 14th - Mission  All Nighter
3065        2026-09-01     801__801 E 14th - Mission  All Nighter
3077        2026-09-01     801__801 E 14th - Mission  All Nighter
2882        2026-09-01   800__800 Rich - Oak Transbay All Nighter
2947        2026-09-01   800__800 Rich - Oak Transbay All Nighter
2957        2026-09-01   800__800 Rich - Oak Transbay All Nighter
2985        2026-09-01   800__800 Rich - Oak Transbay All Nighter
79740       2026-09-01       7__7 Arlington - Shattuck - Stanford
79746       2026-09-01       7__7 Arlington - Shattuck - Stanford
79824       2026-09-01       7__7 Arlington - Shattuck - Stanford
79828       2026-09-01       7__7 Arlington - Shattuck - Stanford
126679      2026-09-01           76__76 Cutting - Market - Moyers
126680      2026-09-01           76__76 Cutting - Market - Moyers
127672      2026-09-01           76__76 Cutting - Market - Moyers
127677      2026-09-01           76__76 Cutting - Market - Moyers
122520      2026-09-01            74__74 San Pablo Dam - 23rd St.
122525      2026-09-01            74__74 San Pablo Dam - 23rd St.
122529      2026-09-01            74__74 San Pablo Dam - 23rd St.
122530      2026-09-01            74__74 San Pablo Dam - 23rd St.
135540      2026-09-01      73__73 73rd Ave. - Coliseum - Airport
135549      2026-09-01      73__73 73rd Ave. - Coliseum - Airport
139120      2026-09-01      73__73 73rd Ave. - Coliseum - Airport
139138      2026-09-01      73__73 73rd Ave. - Coliseum - Airport
122419      2026-09-01                     72__72 CCC - San Pablo
122428      2026-09-01                     72__72 CCC - San Pablo
122444      2026-09-01                     72__72 CCC - San Pablo
122459      2026-09-01                     72__72 CCC - San Pablo
112803      2026-09-01             72M__72M Macdonald - San Pablo
112804      2026-09-01             72M__72M Macdonald - San Pablo
122293      2026-09-01             72M__72M Macdonald - San Pablo
122342      2026-09-01             72M__72M Macdonald - San Pablo
112761      2026-09-01                 72L__72L San Pablo Limited
112772      2026-09-01                 72L__72L San Pablo Limited
112791      2026-09-01                 72L__72L San Pablo Limited
112800      2026-09-01                 72L__72L San Pablo Limited
122257      2026-09-01      71__71 Parchester - Rumrill - Carlson
122258      2026-09-01      71__71 Parchester - Rumrill - Carlson
122260      2026-09-01      71__71 Parchester - Rumrill - Carlson
122262      2026-09-01      71__71 Parchester - Rumrill - Carlson
122264      2026-09-01      71__71 Parchester - Rumrill - Carlson
122266      2026-09-01      71__71 Parchester - Rumrill - Carlson
122267      2026-09-01      71__71 Parchester - Rumrill - Carlson
122269      2026-09-01      71__71 Parchester - Rumrill - Carlson
122200      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
122207      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
122208      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
122209      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
122210      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
122211      2026-09-01      70__70 Rheem - San Pablo Dam - Appian
2544        2026-09-01   703__703 Dubl/Plsntn Transbay Early Bird
2551        2026-09-01   703__703 Dubl/Plsntn Transbay Early Bird
2517        2026-09-01    702__702 Pleas Hill Transbay Early Bird
2532        2026-09-01    702__702 Pleas Hill Transbay Early Bird
2488        2026-09-01  701__701 Pittsburg/BP Transbay Early Bird
2499        2026-09-01  701__701 Pittsburg/BP Transbay Early Bird
152955      2026-09-01        6__6 Berkeley - Telegraph - Oakland
152957      2026-09-01        6__6 Berkeley - Telegraph - Oakland
154066      2026-09-01        6__6 Berkeley - Telegraph - Oakland
154069      2026-09-01        6__6 Berkeley - Telegraph - Oakland
6626        2026-09-01          696__696 Oakland Tech - Montclair
6627        2026-09-01          696__696 Oakland Tech - Montclair
15118       2026-09-01          696__696 Oakland Tech - Montclair
15119       2026-09-01          696__696 Oakland Tech - Montclair
15122       2026-09-01          696__696 Oakland Tech - Montclair
15130       2026-09-01          696__696 Oakland Tech - Montclair
14998       2026-09-01     689__689 De Anza - Soskin - CC College
15005       2026-09-01     689__689 De Anza - Soskin - CC College
15007       2026-09-01     689__689 De Anza - Soskin - CC College
15015       2026-09-01     689__689 De Anza - Soskin - CC College
27510       2026-09-01     689__689 De Anza - Soskin - CC College
27511       2026-09-01     689__689 De Anza - Soskin - CC College
14968       2026-09-01    688__688 St. Mary's College - Montclair
14972       2026-09-01    688__688 St. Mary's College - Montclair
14974       2026-09-01    688__688 St. Mary's College - Montclair
14982       2026-09-01    688__688 St. Mary's College - Montclair
14986       2026-09-01    688__688 St. Mary's College - Montclair
14987       2026-09-01    688__688 St. Mary's College - Montclair
14944       2026-09-01         687__687 Lincoln Middle - Bay Farm
14945       2026-09-01         687__687 Lincoln Middle - Bay Farm
14947       2026-09-01         687__687 Lincoln Middle - Bay Farm
14950       2026-09-01         687__687 Lincoln Middle - Bay Farm
14953       2026-09-01         687__687 Lincoln Middle - Bay Farm
14955       2026-09-01         687__687 Lincoln Middle - Bay Farm
6624        2026-09-01   684__684 El Cerrito - Arlington - Garvin
6625        2026-09-01   684__684 El Cerrito - Arlington - Garvin
24427       2026-09-01   684__684 El Cerrito - Arlington - Garvin
24429       2026-09-01   684__684 El Cerrito - Arlington - Garvin
24432       2026-09-01   684__684 El Cerrito - Arlington - Garvin
24435       2026-09-01   684__684 El Cerrito - Arlington - Garvin
14907       2026-09-01    683__683 Montclair - Bishop O'Dowd High
14908       2026-09-01    683__683 Montclair - Bishop O'Dowd High
14910       2026-09-01    683__683 Montclair - Bishop O'Dowd High
14919       2026-09-01    683__683 Montclair - Bishop O'Dowd High
24407       2026-09-01    682__682 Bishop O'Dowd High - Montclair
24413       2026-09-01    682__682 Bishop O'Dowd High - Montclair
24421       2026-09-01    682__682 Bishop O'Dowd High - Montclair
24423       2026-09-01    682__682 Bishop O'Dowd High - Montclair
31776       2026-09-01    682__682 Bishop O'Dowd High - Montclair
31787       2026-09-01    682__682 Bishop O'Dowd High - Montclair
2358        2026-09-01      681__681 DeJean - Cutting - Macdonald
2359        2026-09-01      681__681 DeJean - Cutting - Macdonald
14850       2026-09-01      681__681 DeJean - Cutting - Macdonald
14856       2026-09-01      681__681 DeJean - Cutting - Macdonald
14858       2026-09-01      681__681 DeJean - Cutting - Macdonald
14865       2026-09-01      681__681 DeJean - Cutting - Macdonald
14829       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
14832       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
14839       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
14844       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
14846       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
14847       2026-09-01    680__680 Bishop O'Dowd High - MacArthur
63668       2026-09-01                     67__67 Spruce - Oxford
63677       2026-09-01                     67__67 Spruce - Oxford
78978       2026-09-01                     67__67 Spruce - Oxford
78982       2026-09-01                     67__67 Spruce - Oxford
14782       2026-09-01       678__678 De Anza - Soskin - Fairmede
14801       2026-09-01       678__678 De Anza - Soskin - Fairmede
14806       2026-09-01       678__678 De Anza - Soskin - Fairmede
14807       2026-09-01       678__678 De Anza - Soskin - Fairmede
19234       2026-09-01       678__678 De Anza - Soskin - Fairmede
19235       2026-09-01       678__678 De Anza - Soskin - Fairmede
6620        2026-09-01        677__677 Montera - Broadway Terrace
6621        2026-09-01        677__677 Montera - Broadway Terrace
14757       2026-09-01        677__677 Montera - Broadway Terrace
14761       2026-09-01        677__677 Montera - Broadway Terrace
14772       2026-09-01        677__677 Montera - Broadway Terrace
14773       2026-09-01        677__677 Montera - Broadway Terrace
14748       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
14749       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
24385       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
24387       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
24394       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
24398       2026-09-01  675__675 Korematsu - El Cerrito - Carlson
14725       2026-09-01     669__669 Soskin Middle - San Pablo Dam
14726       2026-09-01     669__669 Soskin Middle - San Pablo Dam
14744       2026-09-01     669__669 Soskin Middle - San Pablo Dam
14745       2026-09-01     669__669 Soskin Middle - San Pablo Dam
19230       2026-09-01     669__669 Soskin Middle - San Pablo Dam
19231       2026-09-01     669__669 Soskin Middle - San Pablo Dam
6618        2026-09-01   667__667 Korematsu - E.C. - No. Richmond
6619        2026-09-01   667__667 Korematsu - E.C. - No. Richmond
14704       2026-09-01   667__667 Korematsu - E.C. - No. Richmond
14709       2026-09-01   667__667 Korematsu - E.C. - No. Richmond
14716       2026-09-01   667__667 Korematsu - E.C. - No. Richmond
14718       2026-09-01   667__667 Korematsu - E.C. - No. Richmond
6616        2026-09-01  663__663 Encinal - South Shore - High St.
6617        2026-09-01  663__663 Encinal - South Shore - High St.
14684       2026-09-01  663__663 Encinal - South Shore - High St.
14687       2026-09-01  663__663 Encinal - South Shore - High St.
14692       2026-09-01  663__663 Encinal - South Shore - High St.
14695       2026-09-01  663__663 Encinal - South Shore - High St.
6614        2026-09-01   662__662 Skyline High - Broadway Terrace
6615        2026-09-01   662__662 Skyline High - Broadway Terrace
14662       2026-09-01   662__662 Skyline High - Broadway Terrace
14664       2026-09-01   662__662 Skyline High - Broadway Terrace
14667       2026-09-01   662__662 Skyline High - Broadway Terrace
14678       2026-09-01   662__662 Skyline High - Broadway Terrace
14629       2026-09-01        660__660 Montera - Broadway Terrace
14638       2026-09-01        660__660 Montera - Broadway Terrace
14642       2026-09-01        660__660 Montera - Broadway Terrace
14647       2026-09-01        660__660 Montera - Broadway Terrace
14650       2026-09-01        660__660 Montera - Broadway Terrace
14652       2026-09-01        660__660 Montera - Broadway Terrace
90881       2026-09-01               65__65 Grizzly Peak - Euclid
90887       2026-09-01               65__65 Grizzly Peak - Euclid
95248       2026-09-01               65__65 Grizzly Peak - Euclid
95251       2026-09-01               65__65 Grizzly Peak - Euclid
14549       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
14551       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
14553       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
14555       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
14561       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
14567       2026-09-01  658__658 Skyline - Bret Harte - MacArthur
24314       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
24321       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
24322       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
24323       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
24324       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
24327       2026-09-01   657__657 Oak High - Oak Tech - MacArthur
14500       2026-09-01               655__655 Montera - 35th Ave.
14501       2026-09-01               655__655 Montera - 35th Ave.
24107       2026-09-01               655__655 Montera - 35th Ave.
24110       2026-09-01               655__655 Montera - 35th Ave.
24119       2026-09-01               655__655 Montera - 35th Ave.
24121       2026-09-01               655__655 Montera - 35th Ave.
19224       2026-09-01          654__654 Skyline High - 35th Ave.
19225       2026-09-01          654__654 Skyline High - 35th Ave.
24085       2026-09-01          654__654 Skyline High - 35th Ave.