In [2]:
import geopandas as gpd
import gcsfs
import google.auth
import pandas as pd

import world_cup_vars as wc_vars

credentials, _ = google.auth.default()

GCS_FILE_PATH = wc_vars.GCS_FILE_PATH

In [3]:
routes_near_stadium = pd.read_parquet(
    f"{GCS_FILE_PATH}routes_near_poi.parquet", filesystem=gcsfs.GCSFileSystem()
)

In [4]:
route_gdf = pd.read_parquet(
    f"{GCS_FILE_PATH}fct_daily_schedule_rt_route_direction_summary_world_cup.parquet", 
    filesystem = gcsfs.GCSFileSystem(),
    columns = ["service_date", "schedule_name", "feed_key", "route_id", "route_id_cleaned",
               "route_name", "direction_id", "route_type",
               "shape_id", "shape_array_key", 
               "n_trips", "n_shapes", "num_stop_times", "avg_stops_served"
              ],
    filters = [[
        ("schedule_name", "in", wc_vars.socal_names + wc_vars.bay_area_names),
    ]]
).merge(
    routes_near_stadium,
    on = ["schedule_name", "route_name", "direction_id", "shape_array_key"],
    how = "inner"
)

In [8]:
for i in sorted(route_gdf.schedule_name.unique()):
    print(i)
    print(route_gdf[route_gdf.schedule_name == i].route_name.value_counts())
    print("--------------------------------------------")

BART Schedule
route_name
5__Green-S Berryessa/North San Jose to Daly City    29
6__Green-N Daly City to Berryessa/North San Jose    29
3__Orange-N Berryessa/North San Jose to Richmond    29
4__Orange-S Richmond to Berryessa/North San Jose    29
Name: count, dtype: int64
--------------------------------------------
Bay Area 511 ACE Schedule
route_name
ACE__Altamont Commuter Express    29
Name: count, dtype: int64
--------------------------------------------
Bay Area 511 BART Schedule
route_name
Green__Green-S Berryessa/North San Jose to Daly City     22
Green__Green-N Daly City to Berryessa/North San Jose     22
Orange__Orange-N Berryessa/North San Jose to Richmond    22
Orange__Orange-S Richmond to Berryessa/North San Jose    22
Name: count, dtype: int64
--------------------------------------------
Bay Area 511 Caltrain Schedule
route_name
Limited__Limited                                                 34
Express__Express                                                 34
Local Weekday__Local Weekday                                     34
South County__South County South Santa Clara County Connector    32
Local Weekend__Local Weekend                                     12
Name: count, dtype: int64
--------------------------------------------
Bay Area 511 Capitol Corridor Schedule
route_name
CC__CC Capitol Corridor    15
Name: count, dtype: int64
--------------------------------------------
Bay Area 511 Santa Clara Transit Schedule
route_name
21__21 Stanford Shopping Ctr - Santa Clara TC                      46
Orange Line__Orange Line Mountain View - Alum Rock                 46
57__57 Old Ironsides Stn - West Valley Coll                        46
56__56 Lockheed Martin - Monterey & Old Tully                      46
55__55 Old Ironsides Stn - De Anza Coll                            46
47__47 Milpitas BART - Alder Stn via McCarthy Ranch                46
59__59 Valley Med - Baypointe via Alviso                           46
Green Line__Green Line Old Ironsides - Winchester                  38
Blue Line__Blue Line Baypointe - Santa Teresa                      38
20__20 Milpitas BART - Sunnyvale TC                                34
Express 104__Express 104 Milpitas BART - Stanford Research Park    32
ACE Violet__ACE Violet South Milpitas                              32
ACE Brown__ACE Brown North San Jose                                32
ACE Yellow__ACE Yellow South Santa Clara                           32
ACE Red__ACE Red North Sunnyvale                                   32
ACE Purple__ACE Purple West Milpitas                               32
ACE Orange__ACE Orange Mountain View                               32
ACE Green__ACE Green North Santa Clara                             32
ACE Gray__ACE Gray South Sunnyvale                                 32
203__203 Civic Center - Baypointe - Alum Rock                      22
200__200 Baypointe - Mountain View                                 22
GreenS__GreenS Green Line WC26                                      8
BlueS__BlueS Blue Line WC26                                         8
OrangeE__OrangeE Orange Line East Segment WC26                      6
OrangeW__OrangeW Orange Line West Segment WC26                      6
BBWC__BBWC Bus Bridge WC26                                          6
Name: count, dtype: int64
--------------------------------------------
Beach Cities GMV Schedule
route_name
4815__109    58
Name: count, dtype: int64
--------------------------------------------
Big Blue Bus Schedule
route_name
3__3 Lincoln Boulevard/LAX      58
T14__T14 Los Angeles Stadium    16
Name: count, dtype: int64
--------------------------------------------
Culver City Schedule
route_name
6__6 Sepulveda Boulevard           58
6R__Rapid 6 Sepulveda Boulevard    42
Name: count, dtype: int64
--------------------------------------------
G Trans Schedule
route_name
5__5 Line 5                       56
2__2 Line 2                       56
G__G Line G to Manhattan Beach    28
7X__7X Line 7X                    16
2SCH__2SCH Line 2 School           2
Name: count, dtype: int64
--------------------------------------------
LA DOT Schedule
route_name
4278__CE438B                                  36
4291__CE439                                   36
1458__CE438B                                  36
869__CE574                                    36
27__CE438                                     36
712__DASH Chesterfield Square                 28
605__DASH Leimert/Slauson Counterclockwise    27
575__DASH Leimert/Slauson Clockwise           27
716__DASH Vermont/Main Counterclockwise       27
715__DASH Vermont/Main Clockwise              27
Name: count, dtype: int64
--------------------------------------------
LA Metro Bus Schedule
route_name
115__115 Metro Local Line        58
754__754 Metro Rapid Line        58
204__204 Metro Local Line        58
111__111 Metro Local Line        58
40__40 Metro Local Line          58
108__108 Metro Local Line        58
212__212 Metro Local Line        58
210__210 Metro Local Line        58
207__207 Metro Local Line        58
117__117 Metro Local Line        58
206__206 Metro Local Line        58
110__110 Metro Local Line        58
232__232 Metro Local Line        58
120__120 Metro Local Line        58
102__102 Metro Local Line        58
209__209 Metro Local Line        42
211__211/215 Metro Local Line    42
Name: count, dtype: int64
--------------------------------------------
LA Metro Events Schedule
route_name
7__ R7 Newport Transportation Center      2
5__ R5 Downtown Long Beach                2
14__ T14 Downtown Santa Monica            2
13__ T13 Pierce College Station           2
8__ S8 Torrance Transit Center            2
15__ T15 North Hollywood Station          2
10__ S10 Harbor Gateway Transit Center    2
4__ R4 Hawthorne/Lennox Station           2
3__ R3 Crenshaw Station                   2
9__ S9 Culver City Transit Center         2
6__ R6 ARTIC Anaheim Station              2
2__ R2 Union Station                      2
1__ R1 El Camino College                  2
11__ S11 LAX/Metro Transit Center         2
12__ S12 Hotels & Parking LAX             2
Name: count, dtype: int64
--------------------------------------------
LA Metro Rail Schedule
route_name
805__ Metro D Line    56
802__ Metro B Line    56
807__ Metro K Line    56
803__ Metro C Line    56
801__ Metro A Line    56
804__ Metro E Line    56
Name: count, dtype: int64
--------------------------------------------
Metrolink Schedule
route_name
91 Line__91-PV Line Metrolink 91-Perris Valley Line             58
Ventura County Line__VC Line Metrolink Ventura County Line      58
Orange County Line__OC Line Metrolink Orange County Line        58
Antelope Valley Line__AV Line Metrolink Antelope Valley Line    58
San Bernardino Line__SB Line Metrolink San Bernardino Line      58
Riverside Line__RIV Line Metrolink Riverside Line               40
Name: count, dtype: int64
--------------------------------------------
SCVTA Schedule
route_name
21__21 Stanford Shopping Ctr - Santa Clara TC              58
Ornge__Orange Line Mountain View - Alum Rock               58
57__57 Old Ironsides Stn - West Valley Coll                58
56__56 Lockheed Martin - Monterey & Old Tully              58
55__55 Old Ironsides Stn - De Anza Coll                    58
47__47 Milpitas BART - Alder Stn via McCarthy Ranch        58
59__59 Valley Med - Baypointe via Alviso                   58
Green__Green Line Old Ironsides - Winchester               46
Blue__Blue Line Baypointe - Santa Teresa                   46
20__20 Milpitas BART - Sunnyvale TC                        42
104__Express 104 Milpitas BART - Stanford Research Park    40
831__ACE Violet South Milpitas                             40
828__ACE Brown North San Jose                              40
827__ACE Yellow South Santa Clara                          40
826__ACE Red North Sunnyvale                               40
825__ACE Purple West Milpitas                              40
824__ACE Orange Mountain View                              40
823__ACE Green North Santa Clara                           40
822__ACE Gray South Sunnyvale                              40
203__203 Civic Center - Baypointe - Alum Rock              28
200__200 Baypointe - Mountain View                         28
GrenS__GreenS Green Line WC26                              12
BlueS__BlueS Blue Line WC26                                12
OranE__OrangeE Orange Line East Segment WC26               10
OranW__OrangeW Orange Line West Segment WC26               10
BBSB__BBWC Bus Bridge WC26                                 10
Name: count, dtype: int64
--------------------------------------------
Torrance Schedule
route_name
8__8 LINE 8       46
10__10 LINE 10    46
Name: count, dtype: int64
--------------------------------------------

In [30]:
import polars as pl
from great_tables import GT

one_operator = "Big Blue Bus Schedule"
operator_df = route_gdf[route_gdf.schedule_name == one_operator]

operator_wide_df = (
    operator_df
    .sort_values(["schedule_name", "route_name", "direction_id", "service_date"])
    .groupby(["schedule_name", "route_name", "direction_id"])
    .agg({
        "service_date": lambda x: list(pd.to_datetime(x).dt.date),
        "n_trips": lambda x: list(x),
        "num_stop_times": lambda x: list(x),
        "avg_stops_served": lambda x: list(x)
    }).reset_index()
)

(
    GT(pl.from_pandas(operator_wide_df.drop(columns = "service_date")))
    .fmt_nanoplot("n_trips")
    .fmt_nanoplot("num_stop_times")
    .fmt_nanoplot("avg_stops_served")
)

GT(_tbl_data=shape: (4, 6)
┌────────────────┬────────────────┬──────────────┬────────────────┬────────────────┬───────────────┐
│ schedule_name  ┆ route_name     ┆ direction_id ┆ n_trips        ┆ num_stop_times ┆ avg_stops_ser │
│ ---            ┆ ---            ┆ ---          ┆ ---            ┆ ---            ┆ ved           │
│ str            ┆ str            ┆ i64          ┆ list[i64]      ┆ list[i64]      ┆ ---           │
│                ┆                ┆              ┆                ┆                ┆ list[f64]     │
╞════════════════╪════════════════╪══════════════╪════════════════╪════════════════╪═══════════════╡
│ Big Blue Bus   ┆ 3__3 Lincoln   ┆ 0            ┆ [95, 66, … 95] ┆ [6768, 4464, … ┆ [36.0, 36.0,  │
│ Schedule       ┆ Boulevard/LAX  ┆              ┆                ┆ 6840]          ┆ … 36.0]       │
│ Big Blue Bus   ┆ 3__3 Lincoln   ┆ 1            ┆ [95, 67, … 95] ┆ [6171, 4125, … ┆ [33.0, 33.0,  │
│ Schedule       ┆ Boulevard/LAX  ┆              ┆                ┆ 6270]          ┆ … 33.0]       │
│ Big Blue Bus   ┆ T14__T14 Los   ┆ 0            ┆ [14, 14, … 14] ┆ [56, 52, … 56] ┆ [2.0, 2.0, …  │
│ Schedule       ┆ Angeles        ┆              ┆                ┆                ┆ 2.0]          │
│                ┆ Stadium        ┆              ┆                ┆                ┆               │
│ Big Blue Bus   ┆ T14__T14 Los   ┆ 1            ┆ [12, 12, … 12] ┆ [44, 32, … 46] ┆ [2.0, 2.0, …  │
│ Schedule       ┆ Angeles        ┆              ┆                ┆                ┆ 2.0]          │
│                ┆ Stadium        ┆              ┆                ┆                ┆               │
└────────────────┴────────────────┴──────────────┴────────────────┴────────────────┴───────────────┘, _body=<great_tables._gt_data.Body object at 0x7cc7ce523290>, _boxhead=Boxhead([ColInfo(var='schedule_name', type=<ColInfoTypeEnum.default: 1>, column_label='schedule_name', column_align='left', column_width=None), ColInfo(var='route_name', type=<ColInfoTypeEnum.default: 1>, column_label='route_name', column_align='left', column_width=None), ColInfo(var='direction_id', type=<ColInfoTypeEnum.default: 1>, column_label='direction_id', column_align='right', column_width=None), ColInfo(var='n_trips', type=<ColInfoTypeEnum.default: 1>, column_label='n_trips', column_align='center', column_width=None), ColInfo(var='num_stop_times', type=<ColInfoTypeEnum.default: 1>, column_label='num_stop_times', column_align='center', column_width=None), ColInfo(var='avg_stops_served', type=<ColInfoTypeEnum.default: 1>, column_label='avg_stops_served', column_align='center', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7cc7ce6d9c10>, _spanners=Spanners([]), _heading=Heading(title=None, subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7cc7caa19a90>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7cc7cb571050>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7cc7cabfb610>, _formats=[<great_tables._gt_data.FormatInfo object at 0x7cc7d9649dd0>, <great_tables._gt_data.FormatInfo object at 0x7cc7cacc5e10>, <great_tables._gt_data.FormatInfo object at 0x7cc7caa0bb90>], _substitutions=[], _col_merge=[], _transforms=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), summary_row_padding=OptionsInfo(scss=True, category='summary_row', type='px', value='8px'), summary_row_padding_horizontal=OptionsInfo(scss=True, category='summary_row', type='px', value='5px'), summary_row_background_color=OptionsInfo(scss=True, category='summary_row', type='value', value=None), summary_row_text_transform=OptionsInfo(scss=True, category='summary_row', type='value', value='inherit'), summary_row_border_style=OptionsInfo(scss=True, category='summary_row', type='value', value='solid'), summary_row_border_width=OptionsInfo(scss=True, category='summary_row', type='px', value='2px'), summary_row_border_color=OptionsInfo(scss=True, category='summary_row', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), footnotes_marks=OptionsInfo(scss=False, category='footnotes', type='values', value='numbers'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

In [12]:
operator_df.dtypes

service_date         datetime64[ns]
schedule_name                object
feed_key                     object
route_id                     object
route_id_cleaned             object
route_name                   object
direction_id                  int64
route_type                   object
shape_id                     object
shape_array_key              object
n_trips                       int64
n_shapes                      int64
num_stop_times                int64
avg_stops_served            float64
point_of_interest            object
dtype: object

In [19]:
route_gdf.route_type.unique()

array(['3', '2', '1', '0'], dtype=object)

In [3]:
route_feeds = (
    route_gdf
    .groupby(["schedule_name"])
    .agg({"feed_key": "nunique"})
    .reset_index()
)

In [4]:
subset_feeds = pd.read_parquet(
    f"{GCS_FILE_PATH}feeds_world_cup.parquet", 
    filesystem=gcsfs.GCSFileSystem()
)

subset_feeds_counts = (
    subset_feeds
    .groupby("gtfs_dataset_name")
    .agg({"feed_key": "nunique"})
    .reset_index()
    .rename(columns = {"gtfs_dataset_name": "schedule_name"})
)

In [5]:
m1 = pd.merge(
    route_feeds, 
    subset_feeds_counts,
    on = "schedule_name",
    how = "outer",
    indicator=True
)

m1._merge.value_counts()

_merge
both          18
right_only     5
left_only      0
Name: count, dtype: int64

In [6]:
m1[m1._merge== "right_only"]

                schedule_name  feed_key_x  feed_key_y      _merge
0                ACE Schedule         NaN           1  right_only
1             Amtrak Schedule         NaN          28  right_only
10          Caltrain Schedule         NaN           1  right_only
11  Capitol Corridor Schedule         NaN           3  right_only
14         Inglewood Schedule         NaN           2  right_only

In [7]:
m1[(m1._merge=="both") & (m1.feed_key_x != m1.feed_key_y)]

                 schedule_name  feed_key_x  feed_key_y _merge
4   Bay Area 511 BART Schedule         1.0           2   both
15             LA DOT Schedule        11.0          12   both
17    LA Metro Events Schedule         1.0           3   both
18      LA Metro Rail Schedule        19.0          20   both

In [8]:
route_gdf.feed_key.nunique() # this is ok, overcount a couple, because filtering is by name

51

In [9]:
subset_feeds.feed_key.nunique()

91

In [10]:
shape_geom = gpd.read_parquet(
    f"{GCS_FILE_PATH}dim_shape_arrays_world_cup.parquet",
    storage_options = {"token": credentials},
    #columns = ["shape_array_key", "geometry"]
)

In [11]:
shape_geom.shape

(7568, 4)

In [12]:
shape_geom.feed_key.nunique()

87

In [13]:
shape_geom.shape_array_key.nunique()

7568

In [14]:
# Ok, this is just a couple of feeds that were missing before
gdf = pd.merge(
    route_gdf,
    shape_geom,
    on = ["feed_key", "shape_id"],
    how = "left",
    indicator=True
)

gdf._merge.value_counts()

_merge
both          19085
left_only         0
right_only        0
Name: count, dtype: int64

In [16]:
gdf.route_type

AttributeError: 'DataFrame' object has no attribute 'route_type'

In [15]:
gdf = pd.merge(
    route_gdf,
    shape_geom,
    on = "shape_array_key",
    how = "left",
    indicator=True
)

gdf._merge.value_counts()

_merge
both          19085
left_only         0
right_only        0
Name: count, dtype: int64

In [ ]:
def merge_routes_with_shape_geom(
    route_df: pd.DataFrame,
):
    shape_geom = gpd.read_parquet(
        f"{GCS_FILE_PATH}dim_shape_arrays_world_cup.parquet",
        storage_options = {"token": credentials},
        columns = ["feed_key", "shape_id", "shape_array_key", "geometry"]
    )
    
    gdf = pd.merge(
        route_df,
        shape_geom,
        on = ["feed_key", "shape_id"],
        how = "left",
        indicator=True
    )

    gdf = gpd.GeoDataFrame(gdf, geometry = "geometry")
    
    return gdf

In [ ]:
route_gdf2 = route_gdf.pipe(merge_routes_with_shape_geom)

In [ ]:
route_gdf.shape, route_gdf2.shape

In [ ]:
route_gdf2._merge.value_counts()

## filter for operators, then filter for routes

filtering for routes is really time-consuming

can we just do geospatial pass, grab all the `routes` where shapes get within 3 miles or 10 miles of stadium?

In [ ]:
df = pd.read_parquet(
    f"{GCS_FILE_PATH}daily_schedule_rt_route_direction_summary_combined_dates.parquet",
    filesystem = gcsfs.GCSFileSystem(),
)

FutureWarning - `isin` behavior

/tmp/ipykernel_2595/3934463677.py:1: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.

In [ ]:
sofi_dates = [pd.to_datetime(d) for d in wc_vars.sofi_dates]
levi_dates = [pd.to_datetime(d) for d in wc_vars.levi_dates]

In [ ]:
# isin needs to cast to match dtypes, got 
df_socal = df[(df.service_date.isin(sofi_dates)) & (df.schedule_name.isin(wc_vars.socal_names))]
df_norcal = df[(df.service_date.isin(levi_dates)) & (df.schedule_name.isin(wc_vars.bay_area_names))]

In [ ]:
df = pd.concat([df_socal, df_norcal], axis=0, ignore_index=True)

In [ ]:
la_metro_routes = [
    '22__South Bay Dodger Stadium Express',
    '803__ Metro C Line',
    '807__ Metro K Line'
]

ladot_routes = [
    'CE' # commuter express, so many, need to filter these down more
]

In [ ]:
# filter for routes
df[
    (df.schedule_name == "LA DOT Schedule") & 
    (df.route_name.str.contains("CE"))
    ].route_name.value_counts()